import { Inter } from "next/font/google";
import "./globals.css";
// import { Flowbite } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "緬北旅遊網",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* <Flowbite>
        {children}
      </Flowbite> */}
    </html>
  );
}
